export const cityNames = [
    { cityName:"Dehli", cityState:"Dehli",Celicus:"10 °C",cloud:"Mist",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Mumbai", cityState:"Maharashtra",Celicus:"10 °C",cloud:"Haze",nature:"Smoke",img:"./cloudy.svg"},
    { cityName:"Kolkata", cityState:"West Bengal",Celicus:"15 °C",cloud:"Mist",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Bangalore", cityState:"Karnataka",Celicus:"24 °C",cloud:"Clouds",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Chennai", cityState:"Tamil Nadu",Celicus:"26 °C",cloud:"Clouds",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Hyderabad", cityState:"Telangana",Celicus:"23 °C",cloud:"Mist",nature:"Smoke",img:"./cloudy.svg"},
    { cityName:"Ahmadabad", cityState:"Gujarat",Celicus:"10 °C",cloud:"Mist",nature:"Smoke",img:"./sunny.svg"},
    { cityName:"Lucknow", cityState:"Gujarat",Celicus:"21 °C",cloud:"smoke",nature:"smoke",img:"./cloudy.svg"},
    { cityName:"Jaipur", cityState:" Uttar Pradesh",Celicus:"32 °C",cloud:"Mist",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Mirzapur", cityState:" Rajasthan",Celicus:"14 °C",cloud:"Haze",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Ghaziabad", cityState:"Uttar Pradesh",Celicus:"19 °C",cloud:"Haze",nature:"Smoke",img:"./cloudy.svg"},
    { cityName:"Indore", cityState:" Madhya Pradesh",Celicus:"10 °C",cloud:"Mist",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Vadodara", cityState:"Gujarat",Celicus:"19 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Vishakhapatnam", cityState:"Andhra Pradesh",Celicus:"10 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Chinchvad", cityState:"Madhya Pradesh",Celicus:"18 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Patna", cityState:"Bihar",Celicus:"10 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Ludhiana", cityState:"Punjab",Celicus:"10 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Āgra", cityState:"Uttar Pradesh",Celicus:"31 °C",cloud:"Smoke",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Madurai", cityState:"Tamil Nadu",Celicus:"10 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Jamshedpur", cityState:"Jharkhand",Celicus:"10 °C",cloud:"Smoke",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Ujjain", cityState:"Madhya Pradesh",Celicus:"18 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Jhansi", cityState:"Uttar Pradesh",Celicus:"19 °C",cloud:"Mist",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Ulhasnagar", cityState:"Maharashtra",Celicus:"10 °C",cloud:"Smoke",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Davangere", cityState:"Karnataka",Celicus:"10 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Jammu", cityState:"Jammu and Kashmir",Celicus:"20 °C",cloud:"Mist",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Belgaum", cityState:"Karnataka",Celicus:"20 °C",cloud:"Smoke",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Gulbarga", cityState:"Karnataka",Celicus:"33 °C",cloud:"Mist",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"Jamnagar", cityState:"Gujarat",Celicus:"23 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},
    { cityName:"Dhulia", cityState:"Maharashtra",Celicus:"20 °C",cloud:"Smoke",nature:"Cloudy",img:"./sunny.svg"},
    { cityName:"NasGayaik", cityState:"Bihar",Celicus:"22 °C",cloud:"Mist",nature:"Cloudy",img:"./cloudy.svg"},

  ];